[tool.black]
line-length=79
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.coverage.run]
source = ["cvs"]
omit = ["cvs/__main__.py", "setup.py", cvs/__init__.py]